/**
 * Globs the data directories into one `build/catalog.js` module.
 *
 * It does no maths and no network: fonts and palettes arrive already measured and
 * role-assigned from `scripts/fonts.mjs` and `scripts/palettes.mjs`, so a deploy never
 * runs the font or colour toolchain. The one thing it computes is base64 — doing that per
 * request would burn CPU on every visit.
 *
 * Effects are JS modules with functions in them, so they are re-exported by a static
 * import rather than serialized; esbuild inlines them when Wrangler bundles the Worker.
 *
 *   node scripts/build.mjs [--root <dir>] [--out <file>]
 *
 * The counts and effective sizes it prints are informational. This script never fails a
 * build over taste; it fails only when the catalog is internally broken (a font meta whose
 * woff2 is missing, a duplicate id, malformed JSON).
 */
import { glob, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'
import { argv } from 'node:process'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'

const byId = (a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0)

/**
 * @param {string} root
 * @param {string} pattern
 */
async function find(root, pattern) {
  const out = []
  for await (const hit of glob(pattern, { cwd: root })) out.push(hit)
  return out.sort()
}

/**
 * @param {string} file
 */
async function json(file) {
  try {
    return JSON.parse(await readFile(file, 'utf8'))
  } catch (err) {
    throw new Error(`${file}: ${err.message}`)
  }
}

/**
 * Inverse Simpson index: how many items the axis behaves like, given its odds. It is the
 * number that collapses when a weights file over-boosts one item, so it is worth printing
 * even though nothing gates on it.
 *
 * @param {readonly number[]} odds
 */
function effective(odds) {
  const total = odds.reduce((a, b) => a + b, 0)
  if (total === 0) return 0
  const sum = odds.reduce((a, o) => a + (o / total) ** 2, 0)
  return sum === 0 ? 0 : 1 / sum
}

/** @param {readonly {id: string}[]} items */
function assertUnique(items, kind) {
  const seen = new Set()
  for (const item of items) {
    if (seen.has(item.id)) throw new Error(`duplicate ${kind} id: ${item.id}`)
    seen.add(item.id)
  }
}

/**
 * @param {{root?: string, out?: string, quiet?: boolean}} [opts]
 */
export async function build(opts = {}) {
  const root = resolve(opts.root ?? '.')
  const out = resolve(opts.out ?? 'build/catalog.js')

  // --- fonts: meta + the base64 of every file it names ----------------------
  const fonts = []
  for (const rel of await find(root, 'fonts/meta/*.json')) {
    const meta = await json(resolve(root, rel))
    const files = []
    for (const file of meta.files ?? []) {
      const path = resolve(root, `fonts/files/${meta.id}.${file.id}.woff2`)
      let bytes
      try {
        bytes = await readFile(path)
      } catch {
        throw new Error(`fonts/meta/${meta.id}.json names ${meta.id}.${file.id}, but ${path} is missing`)
      }
      files.push({ ...file, bytes: bytes.length, b64: bytes.toString('base64') })
    }
    fonts.push({ ...meta, files })
  }
  fonts.sort(byId)
  assertUnique(fonts, 'font')

  // --- palettes -------------------------------------------------------------
  const palettes = []
  for (const rel of await find(root, 'data/palettes/*.json')) {
    const rows = await json(resolve(root, rel))
    for (const row of rows) palettes.push(row)
  }
  palettes.sort(byId)
  assertUnique(palettes, 'palette')

  // --- presets --------------------------------------------------------------
  const presets = []
  for (const rel of await find(root, 'presets/*.json')) presets.push(await json(resolve(root, rel)))
  presets.sort(byId)
  assertUnique(presets, 'preset')

  // --- effects: static imports, not data ------------------------------------
  const effectFiles = await find(root, 'effects/*.js')
  const imports = effectFiles.map((rel, i) => {
    const spec = relative(dirname(out), resolve(root, rel)).split('\\').join('/')
    return { name: `fx${i}`, spec: spec.startsWith('.') ? spec : `./${spec}` }
  })

  // --- rules ----------------------------------------------------------------
  const deny = (await json(resolve(root, 'data/deny.json')).catch(() => ({ deny: [] }))).deny ?? []
  const weights = await json(resolve(root, 'data/weights.json')).catch(() => ({}))

  const source =
    `// Generated by scripts/build.mjs from ${relative(process.cwd(), root) || '.'}.\n` +
    '// Do not edit; do not commit. Regenerate with: node scripts/build.mjs\n' +
    `${imports.map((i) => `import ${i.name} from '${i.spec}'`).join('\n')}\n` +
    'export default {\n' +
    ` fonts: ${JSON.stringify(fonts)},\n` +
    ` palettes: ${JSON.stringify(palettes)},\n` +
    ` effects: [${imports.map((i) => i.name).join(', ')}],\n` +
    ` presets: ${JSON.stringify(presets)},\n` +
    ` deny: ${JSON.stringify(deny)},\n` +
    ` weights: ${JSON.stringify(weights)},\n` +
    '}\n'

  await mkdir(dirname(out), { recursive: true })
  await writeFile(out, source)

  if (!opts.quiet) report({ fonts, palettes, presets, deny, weights, effectFiles, out, root })
  return { out, fonts, palettes, presets, deny, weights, effects: effectFiles.length }
}

/** Informational only: counts and the effective size (1/Σp²) per axis. */
function report(c) {
  const w = c.weights ?? {}
  const odds = (items, table, fallback = 4) =>
    items.map((x) => Math.max(0, Math.min(16, Math.floor(table?.[x.id] ?? x.odds ?? fallback))))

  const variants = c.fonts.flatMap((f) => f.variants ?? [])
  const roles = c.palettes.flatMap((p) => (p.roles ?? []).map((r) => ({ id: r.o, odds: r.odds })))
  const bytes = c.fonts.flatMap((f) => f.files.map((x) => x.bytes))

  const rows = [
    ['fonts', c.fonts.length, effective(odds(c.fonts, w.f))],
    ['variants', variants.length, effective(odds(variants, null))],
    ['palettes', c.palettes.length, effective(odds(c.palettes, w.p))],
    ['role sets', roles.length, effective(odds(roles, null))],
    ['effects', c.effectFiles.length, null],
    ['presets', c.presets.length, effective(odds(c.presets, w.preset))],
    ['deny rules', c.deny.length, null],
  ]

  const where = relative(process.cwd(), c.out) || c.out
  console.log(`catalog → ${where}`)
  for (const [name, n, eff] of rows) {
    console.log(`  ${name.padEnd(11)} ${String(n).padStart(4)}${eff ? `   effective ${eff.toFixed(1)}` : ''}`)
  }
  if (bytes.length > 0) {
    const max = Math.max(...bytes)
    const mean = Math.round(bytes.reduce((a, b) => a + b, 0) / bytes.length)
    console.log(`  font bytes  mean ${mean} · max ${max}`)
  }
}

if (fileURLToPath(import.meta.url) === resolve(argv[1] ?? '')) {
  const { values } = parseArgs({
    options: { root: { type: 'string', default: '.' }, out: { type: 'string', default: 'build/catalog.js' } },
  })
  await build(values)
}
