/**
 * Globs the data directories into one `build/catalog.js` module.
 *
 * It does no maths and no network: fonts and palettes arrive already measured and
 * role-assigned from `scripts/fonts.mjs` and `scripts/palettes.mjs`, so a deploy never
 * runs the font or colour toolchain.
 *
 * Stub (WP-00): emits an empty catalog with the right shape. WP-10 fills it in.
 *
 *   node scripts/build.mjs [--root <dir>] [--out <file>]
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { parseArgs } from 'node:util'

const { values } = parseArgs({
  options: {
    root: { type: 'string', default: '.' },
    out: { type: 'string', default: 'build/catalog.js' },
  },
})

const root = resolve(values.root)
const out = resolve(values.out)

/** @type {{fonts: unknown[], palettes: unknown[], effects: unknown[], presets: unknown[], deny: unknown[], weights: object}} */
const catalog = { fonts: [], palettes: [], effects: [], presets: [], deny: [], weights: {} }

await mkdir(dirname(out), { recursive: true })
await writeFile(
  out,
  `// Generated by scripts/build.mjs from ${root}. Do not edit; do not commit.\nexport default ${JSON.stringify(catalog, null, 1)}\n`,
)

const counts = Object.entries(catalog)
  .filter(([, v]) => Array.isArray(v))
  .map(([k, v]) => `${k} ${v.length}`)
  .join(' · ')
console.log(`catalog → ${values.out}: ${counts}`)
